/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  frontEnd: [
    {
      type: "autogenerated",
      dirName: "g-fe",
    },
  ],
  backEnd: [
    {
      type: "autogenerated",
      dirName: "g-be",
    },
  ],
  devOps: [
    {
      type: "autogenerated",
      dirName: "g-devops",
    },
  ],
  softSkill: [
    {
      type: "autogenerated",
      dirName: "g-soft",
    },
  ],
};

module.exports = sidebars;
